config/routes.rb
Rails.application.routes.draw do

  root to: "application#home"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'

# Edit all trips for a user
  get '/users/:user_id/trips/edit', to: 'trips#edit', as: 'edit_user_trips'

  resources :users, only: [:new, :create, :edit, :update, :show] do
    resources :trips, only: [:new, :create, :update, :index]
  end

  resources :cities, only: [:show, :index, :new, :create]
  resources :reviews, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/city.rb
class City < ApplicationRecord
  has_many :trips
  has_many :users, through: :trips
  has_many :reviews, through: :trips
  validates :name, uniqueness: true, presence: true

  KEY = "AIzaSyDHo4oNRgoF_vXpEaq7R_6M1RCyyPiQaqo"

  # method to send request to fetch geocode location of a city
  def google_api_fetch
    google_url = "https://maps.googleapis.com/maps/api/geocode/json?address="

    JSON.parse(RestClient.get(google_url + self.name + "&" + KEY))
  end

  # method to update longitude/latitude for a city record
  def gather_api_city_data
    @city_data = google_api_fetch
    address = @city_data["results"][0]["address_components"][0]
    if self.name = address["long_name"]
      self.latitude = @city_data["results"][0]["geometry"]["location"]["lat"]
      self.longitude = @city_data["results"][0]["geometry"]["location"]["lng"]
    end
  end

  # makes a request to a search query
  def google_api_nearby_search
    # requires key, location (lat, long), and radius (defined in meters within. Max is 50,000 meters).
    google_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
    location = "location=#{self.latitude},#{self.longitude}"
    radius = "radius=400"

    JSON.parse(RestClient.get(google_url + location + "&" + radius + "&key=" + KEY))
  end

  # makes a request to obtain more details after making a search request
  def google_api_place_details
     # requires key and place_id (from a search request)
    @location = google_api_nearby_search
    google_url = "https://maps.googleapis.com/maps/api/place/details/json?"
    place_id = "placeid=#{@location["results"][0]["place_id"]}"
    JSON.parse(RestClient.get(google_url + "&" + place_id + "&key=" + KEY))
  end

  def gather_api_photo_data
    # requires key, photoreference, and max_height or max_width
    @request = google_api_place_details
    google_url = "https://maps.googleapis.com/maps/api/place/photo?"
    max_width = "maxwidth=400"
    @photos = []
    @request["result"]["photos"].each.with_index do |photo_link, index|
      photo_reference = "photoreference=#{@request["result"]["photos"][index]["photo_reference"]}"
      @photos << "#{google_url}&#{max_width}&#{photo_reference}&key=#{KEY}"
    end
    @photos
  end



end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :trip
  validates :rating, :inclusion => { :in => 1..10}

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_one :review

  def city_name
    city.name
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :bio, presence: true
  validates :password, presence: true, on: :create

  has_many :trips
  has_many :cities, through: :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home

  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
   User.find(session[:user_id]) if logged_in?
  end


  private

    def require_login
      return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :require_login

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if City.find_by(id: @city.id)
      render new_city_path
    else
      @city.gather_api_city_data
      @city.save
      redirect_to cities_path
    end
  end

  def index
    @cities = City.all.sort_by{|city| city.name}
    @user = User.find(session[:user_id])
  end

  def show
    @city = City.find(params[:id])
    @city_data = @city.gather_api_city_data
    @photos = @city.gather_api_photo_data
    @user = User.find(session[:user_id])
    @trips = Trip.select{|trip| trip.city_id == @city.id}
    @reviews = @city.trips.select { |trip| trip.review if trip.review != nil}
  end

  private

  def city_params
    params.require(:city).permit(:name, :latitude, :longtitude, :country, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @user = User.find(session[:user_id])
  end

  def create
    @review = Review.create(review_params)
    @city = @review.trip.city_id
    redirect_to city_path(@city)
  end

  def show
    @review = Review.find(params[:id])
    @reviews = @user.trips.all
  end

  private
    def review_params
      params.require(:review).permit(:trip_id, :description, :rating)
    end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.all
    @user = User.find(params[:user_id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @user = User.find(params[:user_id])
    params["status"].each do |city_id, status|
       @trip = Trip.find_by(user_id: params[:user_id], city_id: city_id.to_i)
      if @trip
        @trip.status = status
        @trip.save
      else
         @trip = Trip.create(user_id: params[:user_id], city_id: city_id.to_i, status: status)
      end
    end
    redirect_to user_trips_path(@user)
  end

  def edit
    @user = User.find(params[:user_id])
    @cities = City.all.sort_by{|city| city.name}
    @trips = @user.trips
  end

  def update
    @user = User.find(params[:user_id])
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def show
    @user = User.find(params[:id])
    @trips = @user.trips.all
  end


  private

  def user_params
    params.require(:user).permit(:username, :first_name,:last_name, :email, :bio, :admin, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Home Page</title>
    </head>
    <body class="main">
      <div class="container-1">
        <img src="images/TravelShare_Logo.jpg" alt="Travel Share"><br> <br>

        <div class="button">
          <%= link_to "Sign Up", new_user_path %>
        </div>
        <div class="button">
          <%= link_to "Sign In", login_path %>
        </div>
      </div>
    </body>
</html>

app/views/cities/_city_map.html.erb
<div id="map"></div>
<script>
  function initMap() {
    var uluru = { lat: <%= city.latitude %>, lng: <%= city.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: uluru,
      styles: [
    {
        "stylers": [
            {
                "hue": "#bbff00"
            },
            {
                "weight": 0.5
            },
            {
                "gamma": 0.5
            }
        ]
    },
    {
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "stylers": [
            {
                "color": "#a4cc48"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#ffffff"
            },
            {
                "visibility": "on"
            },
            {
                "weight": 1
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "gamma": 1.14
            },
            {
                "saturation": -18
            }
        ]
    },
    {
        "featureType": "road.highway.controlled_access",
        "elementType": "labels",
        "stylers": [
            {
                "saturation": 30
            },
            {
                "gamma": 0.76
            }
        ]
    },
    {
        "featureType": "road.local",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "weight": 0.4
            },
            {
                "lightness": -8
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "color": "#4aaecc"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "stylers": [
            {
                "color": "#718e32"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "stylers": [
            {
                "saturation": 68
            },
            {
                "lightness": -61
            }
        ]
    },
    {
        "featureType": "administrative.locality",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "weight": 2.7
            },
            {
                "color": "#f4f9e8"
            }
        ]
    },
    {
        "featureType": "road.highway.controlled_access",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "weight": 1.5
            },
            {
                "color": "#e53013"
            },
            {
                "saturation": -42
            },
            {
                "lightness": 28
            }
        ]
    }
]
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>


<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHo4oNRgoF_vXpEaq7R_6M1RCyyPiQaqo&callback=initMap">
</script>

app/views/cities/index.html.erb
<%= render "layouts/navbar" %>
<div class ="backimg">
<div class ="citylist">
  <%= link_to "Add City", new_city_path %>
<table class= "citylisttable" >
  <tr>
    <th>City</th>
    <th>Country</th>
  </tr>

  <% @cities.each do |city| %>
  <tr>
    <td><%= link_to city.name, city_path(city)%></td>
    <td><%= city.country%></td>
  </tr>
  <% end %>
</table>
</div>
</div>

app/views/cities/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

  </head>
  <body>
    <h1>Add a new city</h1>
      <%= form_for(@city) do |f| %>
        <%= f.label :name %> <br>
        <%= f.text_field :name %> <br>

        <%= f.label :country %> <br>
        <%= f.text_field :country %> <br>

        <%= f.label :description %> <br>
        <%= f.text_field :description %> <br>

        <%= f.submit %>
      <% end %>
  </body>
</html>

app/views/cities/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
  <%= render 'layouts/navbar'%>
    <div class="city-header">
      <h2><%= @city.name %>, <%= @city.country %></h2>
    </div>

    <div class="image-container">
      <div id="slider">
        <ul class="slides">
          <% @photos.each do |photo| %>
            <li class="slide"><img src="<%= photo %>" alt=""></li>
          <% end %>
          <li class="slide"><img src="<%= @photos[0] %>" alt=""></li>
        </ul>
      </div>
    </div>

  <%= link_to "Add Review", new_review_path %>
  <div>
    <% @reviews.each do |trip| %>
      <h2><%= trip.user.username %></h2>
      <h3><%= trip.review.rating %> - <%= trip.review.description %></h3>
    <% end %>
  </div>

    <div class="city-info">
      <h3><%= @city.description %></h3>
    </div>

    <a href="http://maps.google.com/?q=<%=@city.latitude%>,<%=@city.longitude%>">Google Maps</a><br />
    <%= render partial: 'city_map', locals: {city: @city} %>

    <div class="list-container">
      <div class="list-container-list">
        <h3>Explored</h3>
        <% @trips.each do |trip|%>
          <% if trip.status == "Visited"%>
            <p><%= link_to trip.user.username, user_trips_path(trip.user) %> </p>
          <% end %>
        <% end %>
      </div>
      <div class="list-container-list">
        <h3>Bucket List</h3>
        <% @trips.each do |trip|%>
          <% if trip.status == "Wished"%>
            <p><%= link_to trip.user.username, user_trips_path(trip.user) %> </p>
          <% end %>
        <% end %>
      </div>
    </div>

  </body>
  <script>
    //configuration
    $(function() {
      var width = 400;
      var animationSpeed = 1000;
      var pause = 3000;
      var currentSlide = 1;

    // cache DOM
      var $slider = $('#slider');
      var $slideContainer = $slider.find('.slides');
      var $slides = $slideContainer.find('.slide');
      var interval;

      function startSlider() {
        interval = setInterval(function() {
          $slideContainer.animate({'margin-left': '-='+width}, animationSpeed, function() {
            if (++currentSlide === $slides.length) {
              currentSlide = 1;
              $slideContainer.css('margin-left', 0);
            }
          });
        }, pause);
      }

      function pauseSlider() {
        clearInterval(interval);
      }

      $slideContainer.on('mouseenter', pauseSlider).on('mouseleave', startSlider);
      startSlider();

    });
  </script>

</html>

app/views/layouts/_navbar.html.erb
<div class="example3">
   <nav class="navbar navbar-inverse navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar3">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>
       <div id="navbar3" class="navbar-collapse collapse">
         <ul class="nav navbar-nav navbar-right">
           <li class="active"><a href="<%=user_trips_path(@user)%>">My Travels</a></li>
           <li><a href="<%= cities_path%>">Destinations</a></li>
           <li><a href="<%=user_path(@user) %>">My Profile</a></li>
          
           <li> <%= link_to "Log out", logout_path, method: "delete", options: {class: "glyphicon glyphicon-log-out"}%></li>
         </ul>
           </li>
         </ul>
       </div>
       <!--/.nav-collapse -->
     </div>
     <!--/.container-fluid -->
   </nav>
 </div>

app/views/layouts/_user_icon.html.erb
<!DOCTYPE html>
<html>
  <body>

  <img src="https://camo.githubusercontent.com/341831200626efe3e0cf83317801fcac2200fbe2/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323639323831302f323130343036312f34643839316563302d386637362d313165332d393230322d6637333934306431306632302e706e67" style="width:150px;height:200px;">

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelShare</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <!--  navbar -->


    <%= yield %>
  </body>
</html>

app/views/reviews/_new.html.erb
<br>
<br>
<h3>Reviews</h3>
<br>
<%= form_for city_path action: "post" do |f| %>
  <%= f.label "Post Your Review Here:" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <%= f.submit "Submit Review"%>
<% end %>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="review-form">
      <h2>Review Form</h2>
      <%= form_for @review do |f| %>
        <%= f.label "Review" %> <br>
        <%= f.text_area :description %> <br>

        <%= f.label "Rating" %> <br>
        <%= f.number_field :rating, in: 1..10 %> <br> <br>

        <%= f.label :trip_id %>
        <%= f.collection_select :trip_id, @user.trips, :id, :city_name %>

        <%= f.submit %>
      <% end %>
    </div>
  </body>
</html>

app/views/trips/edit.html.erb
<%= render 'layouts/navbar'%>
<div class="editlist">
<h2>Edit Trips</h2>

<%= form_for @user, url: user_trips_path, method: :post do |f|%>
<p><%= f.submit "Update Trips"%></p>
<table>
  <tr>
    <th>City</th>
    <th>Status</th>
  </tr>

  <%  @cities.each do |city| %>
  <tr>
      <td><%= city.name %></td>
      <td>
        <input type="radio" id="<%= city.id %>" name="[status]<%= city.id %>" value="Visited" <%= checked="checked" if !@trips.find_by(city_id: city.id).nil? && @trips.find_by(city_id: city.id).status == "Visited"  %>/>
        Visited
        <input type="radio" id="<%= city.id %>" name="[status]<%= city.id %>" value="Wished" <%= checked="checked" if !@trips.find_by(city_id: city.id).nil? && @trips.find_by(city_id: city.id).status == "Wished"  %> />
        Wished
      </td>
    </tr>

  <% end %>
</table>
<% end %>
</div>

app/views/trips/index.html.erb
<%= render 'layouts/navbar'%>
<h1 class="cityindexheader"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %>'s Travel Adventures</h1>
<div class="list-container">
  <div class="list-container-list">
    <h3>Explored</h3>
    <% @user.trips.each do |trip|%>
      <% if trip.status == "Visited"%>
        <p><%= link_to trip.city.name, city_path(trip.city) %> </p>
      <% end %>
    <% end %>
  </div>
  <div class="list-container-list">
    <h3>Bucket List</h3>
    <% @user.trips.each do |trip|%>
      <% if trip.status == "Wished"%>
        <p><%= link_to trip.city.name, city_path(trip.city) %> </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="edit-profile">

<h1>Edit Your Profile</h1>
<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :first_name, "First Name:" %><br>
    <%= f.text_field :first_name %><br>
    <br>
  </div>

  <div class="field">
    <%= f.label :last_name, "Last Name:" %><br>
    <%= f.text_field :last_name %><br>
    <br>
  </div>

  <div class="field">
    <%= f.label :bio, "About Me:" %><br>
    <%= f.text_area :bio %><br>
    <br>
  </div>

  <div class="actions">
    <%= f.submit "Save Changes"%>
  </div>

<% end %>

<br>
<br>

<%= link_to 'View Your Profile', user_path %>
</div>

app/views/users/index.html.erb
<!-- <%= render 'layouts/navbar' %>

<h1> Travelers </h1>
<% @users.each do |user| %>
  <%= link_to "#{user.username}", user_trips_path(@user) %><br>

<% end %> -->

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body class="signup">
    <h1 class="header">Create an Account</h1> <br>
    <% if @user.errors.any? %>
      <div id="container">
        <h3>
          <b>
            Uh-oh! <%= pluralize(@user.errors.count, "error") %> prohibited you from creating an account:
          </b>
        </h3>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div> <!-- container -->
    <% end %>

    <%= form_for(@user) do |f|%>
      <form>
        <div class="container">
        <p class="sign-up-field"><%=f.label "Username"%></p>
        <%= f.text_field :username%>

        <p class="sign-up-field"><%=f.label "First Name"%></p>
        <%= f.text_field :first_name%>

        <p class="sign-up-field"><%=f.label "Last Name"%></p>
        <%= f.text_field :last_name%>

        <p class="sign-up-field"><%=f.label "Email" %></p>
        <%= f.email_field :email%>

        <p class="sign-up-field"><%=f.label "About Me:" %></p>
        <%= f.text_area :bio%>

        <p class="sign-up-field"><%=f.label "Password" %></p>
        <%= f.password_field :password%>

        <p class="sign-up-field"><%=f.label "Password Confirmation" %></p>
        <%= f.password_field :password_confirmation%>
<br>
<br>
        <%= f.submit "Start your travel journey!"%>
        </div>

      </form>
    <%end %>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body class="profile">
    <%= render "layouts/navbar" %>
    <div class="user-profile">
      <h1>
        <%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}"%>
      </h1>
      <div class="pic">
        <%= render "/layouts/user_icon" %>
      </div>

      <div>
        <p><strong>About Me:</strong> <%= @user.bio %></p>
        <p><strong>Email:</strong>  <%= @user.email %></p>
        <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
        <p><%= link_to 'Edit Trips', edit_user_trips_path(@user) %></p>
      </div>
    </div>
  </body>
</html>